### ISSUE TITLE
domain snow.rs expired

### ISSUE THREAD

**Issue by Ahacad** [mcginty/snow#124]
You might want to renew it. :)

**Comment by mcginty** [comment]
Oops! Thanks, good catch. A squatter sniped it so I'll just remove it as an official domain for now and setup an alert in case anyone tries any funny business.

**Comment by 5225225** [comment]
Did you mean to remove the domain from the `Cargo.toml`? The `snow.rs` domain still shows on the crates.io page, which doesn't look great. (Also means it's harder to get to the docs, since the domain's used for docs as well)

**Comment by Gowee** [comment]
Just find snow.rs is now available for registering.

**Comment by mcginty** [comment]
Yeah, I think it's not worth the money honestly to have a snow.rs - there's no reference to it anywhere in any recent releases, and GitHub is a reasonable homepage for it for now :). Thanks for the heads-up though @Gowee.
