### ISSUE TITLE
Off by one error allows invalid nonce usage

### ISSUE THREAD

**Issue by kjvalencik** [mcginty/snow#150]
Per the spec, the maximum usable nonce value is `2^64 - 2` and not `2^64 - 1`.

> The maximum n value (2^64 - 1) is reserved for other use. If incrementing n results in `2^64 - 1`, then any further EncryptWithAd() or DecryptWithAd() calls will signal an error to the caller.

http://www.noiseprotocol.org/noise.html#the-cipherstate-object

These two usages should be slightly re-written:

```diff
+        if self.n == u64::MAX { return Err(StateProblem::Exhausted); }
         let len = self.cipher.encrypt(self.n, authtext, plaintext, out);
+        self.n += 1;
-        self.n = self.n.checked_add(1).ok_or(StateProblem::Exhausted)?;
```

https://github.com/mcginty/snow/blob/077bb35e840f8899d7038e4bfd569e49aeb98f9c/src/cipherstate.rs#L39
https://github.com/mcginty/snow/blob/077bb35e840f8899d7038e4bfd569e49aeb98f9c/src/cipherstate.rs#L59

**Comment by mcginty** [comment]
Oh great catch. Thank you, I'll fix this and push a patch release.
