### ISSUE TITLE
Can't run the client mode of example `simple`

### ISSUE THREAD

**Issue by openaphid** [mcginty/snow#178]
It's a minor issue. `cargo run --example simple` can't run the client mode, as `if matches.contains_id("server")` is always `true` .
https://github.com/mcginty/snow/blob/009411d2035a77ece57b0a6873169de7693a0aa0/examples/simple.rs#L27-L36

After checking the source code of `clap`, it turns out the macro `arg!` always insert a `SetTrue` action to the arg which makes `contains_id` always return `true`.

https://github.com/clap-rs/clap/blob/cbc9c9dd44fc4be25c196213d508b9d2a9c282f3/clap_builder/src/macros.rs#L204C27-L204C27

**Comment by BlackHoleFox** [comment]
Funnily enough my https://github.com/mcginty/snow/pull/175 cleanup PR would fix this as well.
