### ISSUE TITLE
A lot of structs don't implement Debug trait.

### ISSUE THREAD

**Issue by ozkriff** [mcginty/snow#18]
Is it on purpose?

**Comment by mcginty** [comment]
>Is it on purpose?

@ozkriff nope, they're mostly just not implemented. PRs welcome )).

**Comment by mcginty** [comment]
>> PRs welcome ...

@ozkriff I think a lot of these structs will require custom `impl Debug`s.

**Comment by mcginty** [comment]
Just added a very basic `Debug` impl for `Session`, `HandshakeState`, and `TransportState`, which are the most visible structs. Feel free to open specific issues for more details or implementing Debug in more of the structs/enums.
