### ISSUE TITLE
is_payload_encrypted is confusing

### ISSUE THREAD

**Issue by aep** [mcginty/snow#21]
in IX, the second package from the responder is supposed to be encrypted
```
IX
    -> s, e
    <- e, ee, se, s, es  (payload encrypted with es)
```
but is_payload_encrypted() returns false before calling write_message in that state

i'm guessing this makes sense, since it didn't mix the key yet before write_message, but it's very confusing, because that means you cant use is_payload_encrypted to check for encryption _before_ sending

**Comment by mcginty** [comment]
I think for now I will just remove the method since it's not the correct implementation and will just cause confusion.

**Comment by aep** [comment]
Hm. I'm using it now the way it is. (asserting after write_message but before sending it on wire)
