### ISSUE TITLE
udp / setnonce

### ISSUE THREAD

**Issue by aep** [mcginty/snow#30]
missing SetNonce as well as a way to retreive the nonce.

i'm not sure if that's a good api tho to implement udp. Would it make sense to have a write_stateless or something that takes the nonce and does _not_ mutate the current counter?

**Comment by aep** [comment]
oops, SetNonce does exist:  https://docs.rs/snow/0.3.0-alpha5/snow/enum.Session.html#method.set_receiving_nonce

feeels still like a strange api. any opinion on a stateless write/read ?

**Comment by mcginty** [comment]
I agree, I think SetNonce in this library is clunky and error-prone (the design makes it too easy to catastrophically reuse nonces). If you check out the `wireguard` branch, I added an AsyncTransportState alongside TransportState which is basically what you describe, and it also implements Clone for use in multitheading.

**Comment by aep** [comment]
i'm taking alot of inspiration from wireguard, so this already sounds great.

this api makes alot of sense imp https://github.com/mcginty/snow/blob/wireguard/src/async_transportstate.rs#L39

**Comment by mcginty** [comment]
cool, I was planning on releasing 0.3 soon so let's plan on this for 0.4 👍

**Comment by kpcyrd** [comment]
Talking about wireguard, if we want to make sure that the user of the library can't possibly ever process a replayed message, we could (in udp mode) enforce the nonce system that wireguard uses, which are TAI64N timestamps:

> To prevent [replay attacks], a 12-byte TAI64N [7] timestamp is included, encrypted and authenticated, in the first message. The responder keeps track of the greatest timestamp received per peer and discards packets containing timestamps less than or equal to it. (In fact, it does not even have to be an accurate timestamp; it simply must be a per-peer monotonically increasing 96-bit number.)

https://cr.yp.to/libtai/tai64.html

I would also argue that Async is a bad name for udp mode as it could be easily confused with non-blocking io like tokio/futures.

**Comment by aep** [comment]
Not sure what the added benefit of a timestamp is over a monotonous counter. I guess it's because wireguard has to avoid replay of the first packet. That seems rather wireguard specific and only relevant to IK. 

Agree on the async tho. How about UnorderedTransport ?

**Comment by mcginty** [comment]
A noise library should have no concept of time, a TAI64N-based counter is a prime example for an external nonce supplier :).

Agree that Async is confusing. In a length-apathetic world it would be ExplicitNonceTransportState but that is too much of a mouthful. How bout Stateless?

**Comment by aep** [comment]
Stateless is great.

**Comment by mcginty** [comment]
Ok, I've started adding a stateless transport mode in https://github.com/mcginty/snow/tree/0.4. Still a lot of refactoring and testing that needs to be done before it's ready.

**Comment by mcginty** [comment]
In 0.4.0.
