### ISSUE TITLE
read_message_with_nonce should be const

### ISSUE THREAD

**Issue by aep** [mcginty/snow#32]
read_message_with_nonce takes a &mut self.
I think it should take a const self instead to make sure no state gets modified.
I'm intending to move replay-protection to *after* decryption to measure packet duplication, but if read_message_with_nonce modifies state, that might be a security issue.

**Comment by mcginty** [comment]
Nice catch.

**Comment by mcginty** [comment]
I pushed a 0.4.0-alpha2 release with the change.

**Comment by aep** [comment]
thank you!
