### ISSUE TITLE
add noise spec compliant rekey functionality

### ISSUE THREAD

**Issue by david415** [mcginty/snow#35]
Greetings,

As per noise spec section 4.2 there ought to be a rekey function defined as:

"""REKEY(k): Returns a new 32-byte cipher key as a pseudorandom function of k. If this function is not specifically defined for some set of cipher functions, then it defaults to returning the first 32 bytes from ENCRYPT(k,    maxnonce, zerolen, zeros), where maxnonce equals 264-1, zerolen is a zero-length byte sequence, and zeros is a sequence of 32 bytes filled with zeros.
"""

I am currently using snow to write a mixnet link layer wire protocol and our design requires this rekey functionality. I have found that with the current snow API it is NOT possible to implement this rekey functionality externally in my own library because the snow Session's write_message_with_nonce method only allows being called when in StatelessTransport mode.

**Comment by david415** [comment]
As an example, here's the golang noise library's implementation of this rekey function:
https://github.com/flynn/noise/blob/master/state.go#L65-L71

**Comment by mcginty** [comment]
https://docs.rs/snow/0.4.0/snow/enum.Session.html#method.rekey should make it possibly to implement this in the client code, no? I think the rekey API you cited in the docs is new and will be something to target for snow 0.5 perhaps.

**Comment by geogriff-signal** [comment]
somehow i didn't notice the above PR, and sadly wrote my own implementation already. i do believe my implementation is more flexible, as PR #36 only allows to rekey both initiator and responder together (which i'm not sure how you'd even manage to synchronize in most application protocols), whereas my interface allows for rekeying modes such as continuous rekeying, as mentioned in the Noise spec.

**Comment by david415** [comment]
i really do not care which PR is merged. Just pick one and merge it soon before the next drone strike (or whatever human rights violation we are trying to prevent with math)

As for flexibility. @geogriff-signal your assertion that my PR is not useful is unfounded. My mixnet uses it just fine: Katzenpost mix network rekeys after every message sent! Here's our specification: https://github.com/katzenpost/docs/blob/master/specs/wire-protocol.rst
and our implementation in golang: https://github.com/katzenpost/core/blob/master/wire/session.go

**Comment by mcginty** [comment]
Sorry for the lag in getting this into the library. My excuses can be counted in the stars.

Thankfully snow is (or, should be) well-divorced from any tools used to prevent real-world harm. Remember that this code has not yet received a formal audit (...but if anyone is interested in doing so or working out a grant for one, you know where to contact me).

**Comment by david415** [comment]
i am writing a mix network which will use a snow based link layer to connect the mixes. so... at least in theory one day hopefully it should prevent murder.

**Comment by david415** [comment]
i guess we can close this ticket now that the PR was squashed and merged
https://github.com/mcginty/snow/pull/42

**Comment by mcginty** [comment]
Thanks!
