### ISSUE TITLE
Drop rustc-serialize dependency

### ISSUE THREAD

**Issue by dtolnay** [mcginty/snow#4]
It has been deprecated: [announcement](https://users.rust-lang.org/t/deprecation-of-rustc-serialize/10485?u=dtolnay).

Is there any functionality you would require from Serde or another library before this would be possible?

**Comment by mcginty** [comment]
Thanks, yeah I think that's only used for debug output and JSON parsing for the test vectors, so shouldn't be hard to be replaced by https://crates.io/crates/hex and Serde.

**Comment by mcginty** [comment]
Closed in https://github.com/mcginty/snow/commit/0e722b2fb7fa5a62a639c405e936fb2ed16af1f2
