### ISSUE TITLE
build fails, all of them fail to build

### ISSUE THREAD

**Issue by david415** [mcginty/snow#45]
Hi Jake,

Snow doesn't build anymore... at all.

On the crates page (https://crates.io/crates/snow)
you have specified snow = "0.4.2" however the latest
git tag is "0.4.0". This tag fails to build and the master
branch fails to build.

Your latest release is marked as v0.3.0 via github
however that no longer builds because older versions of x25519-dalek have
been yanked:

HEAD is now at 9b16056... 0.3.0
user@computer:~/code/snow$ cargo build
    Updating crates.io index
error: failed to select a version for the requirement `x25519-dalek = "^0.2"`
  candidate versions found which didn't match: 0.4.4, 0.4.3, 0.4.2, ...
  location searched: crates.io index
required by package `snow v0.3.0 (/home/user/code/snow)`
user@computer:~/code/snow$

Please let me know when	you've fixed this situation
and I'm	sorry to bring you this	bad news. :)

Sincerely,
David

**Comment by david415** [comment]
I also tried building git commit id 2f1745908fa7b4dc34f74d94158903baa703a5ef which should have been tagged as 0.4.2 and it fails to build with a bunch of rand trait errors:

```
error[E0277]: the trait bound `rand_pcg::Mcg128Xsl64: rand_core::SeedableRng` is not satisfied
  --> /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/rand-0.6.5/src/rngs/small.rs:96:6
   |
96 | impl SeedableRng for SmallRng {
   |      ^^^^^^^^^^^ the trait `rand_core::SeedableRng` is not implemented for `rand_pcg::Mcg128Xsl64`

error[E0277]: the trait bound `rand_hc::Hc128Rng: rand_core::SeedableRng` is not satisfied
  --> /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/rand-0.6.5/src/rngs/std.rs:55:6
   |
55 | impl SeedableRng for StdRng {
   |      ^^^^^^^^^^^ the trait `rand_core::SeedableRng` is not implemented for `rand_hc::Hc128Rng`

error[E0277]: the trait bound `rand_isaac::IsaacRng: rand_core::SeedableRng` is not satisfied
  --> /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/rand-0.6.5/src/deprecated.rs:50:6
   |
50 | impl SeedableRng for IsaacRng {
   |      ^^^^^^^^^^^ the trait `rand_core::SeedableRng` is not implemented for `rand_isaac::IsaacRng`
...
```

**Comment by mcginty** [comment]
Thanks @brycx for the related issue!

@david415 good idea. I made a signed release for the latest stable version (https://github.com/mcginty/snow/releases/tag/v0.4.2)

Closing since this isn't really a snow problem.
