### ISSUE TITLE
Plans for tokio integration

### ISSUE THREAD

**Issue by alanhoff** [mcginty/snow#5]
Hello there! I would like to know if there are any plans for creating and acceptor on top of [`tokio::net::TcpStream`](https://docs.rs/tokio/0.1.1/tokio/net/struct.TcpStream.html).

Thanks!

**Comment by mcginty** [comment]
Hey Alan! Noise is a framework for making protocols, but is not itself a protocol. By that I mean, a Noise transport packet doesn't include the necessary things like a length header to distinguish packets sent over a stream transport like TCP, so putting Tokio support in Snow itself wouldn't be very helpful.

There's currently work being done to create a "NoiseSocket" spec, whose library would be the place for mio/tokio support.

If you feel there's a justification to adding support for Futures in Snow, though, let me know and we can talk about that to see if it makes sense.

**Comment by alanhoff** [comment]
I'm really thankful for your reply and patience.

I have a pet project and was looking for ways to implement secure networking between nodes without the SSL/TLS config hurdle, I think I misinterpreted your [exemple](https://github.com/mcginty/snow/blob/d767a58db51c5e6f5364c87707ed37c0898af7c5/examples/simple.rs#L47) as being a solution.

I didn't knew about the NoiseSocket extension and it makes perfect sense to wait for it before implementing any stream abstraction. Besides the lack of padding, and please pardon my crypto ignorance, is your example less secure than the same example implemented over NoiseSocket would be? I understand it's way less flexible since it lacks protocol protocol change, fallbacks and reinitialization request but it may still be useful in scenarios where peers are strictly similar.

As you noticed I would prefer spending my time with this exciting protocol rater than configuring certificates 😅
