### ISSUE TITLE
impl Random for OsRng {}. in wrong file

### ISSUE THREAD

**Issue by aep** [mcginty/snow#54]
impl Random for OsRng {}

should be in types.rs, since default.rs is not built if you exclude the default feature.
rust doesnt allow impl the trait as a user either

**Comment by mcginty** [comment]
Sorry for the delayed response!

In this case, `OsRng` is part of the `rand` crate, but not the `rand_core` crate, so it is dependent on the default resolver.

**Comment by aep** [comment]
so you can disable the default resolver, which currently doesn't compile for embedded.

you can't impl Random for OsRng {} in a user defined resolver, so after disabling the default resolver there is no way to impl Random

**Comment by mcginty** [comment]
Ahh, gotcha. Well, it's not the prettiest solution but you can work around that by creating your own struct and storing an `OsRng` inside, and then implementing `Random` for that.

Alternatively, I could introduce another feature separate from default-resolver that depends on the `rand` crate and has the impl you're looking for.

**Comment by mcginty** [comment]
I'll close this unless I'm mistaken here - in which case, please feel free to re-open!
