### ISSUE TITLE
snow-multipsk.txt and unnecessary init_remote_static/resp_remote_static values

### ISSUE THREAD

**Issue by Metalnem** [mcginty/snow#6]
In protocols where remote party is sending its static public key to the local party (or vice versa), the local party doesn't have the knowledge of that key in advance. However, the test vectors in the snow-multipsk.txt file have the init_remote_static and/or resp_remote_static value set anyway (Noise_XXpsk0+psk1_25519_AESGCM_SHA256 is one example of that). The spec for the ReadMessage says:

> For "s": Sets temp to the next DHLEN + 16 bytes of the message if HasKey() == True, or to the next DHLEN bytes otherwise. Sets rs (which must be empty) to DecryptAndHash(temp).

Initializing the Noise protocol from the values in the test vectors thus violates the spec. In contrast, test vectors in cacophony.txt don't have this issue.

**Comment by Metalnem** [comment]
Sorry if I wan't clear enough! Generator is creating correct vectors, but it's also including redundant data.

For example, XX vectors contain init_remote_static, which is redundant. If you just read all the values from the test vectors, you will end up with initialized rs variable. When the responder sends his s value, you could just overwrite your local rs (which will be the same in this case), but the spec mandates that rs should be empty at that moment. That's why I think the test vectors should not contain redundant values.

**Comment by Metalnem** [comment]
One more thing: I have removed the redundant values manually (I needed to do that for my implementation of Noise), here is how the file looks after that:

https://raw.githubusercontent.com/Metalnem/noise/master/Noise.Tests/Vectors/snow-multipsk.txt

I would have modified the vector generator myself and submitted the pull request, but I'm not familiar with Rust :)

**Comment by mcginty** [comment]
@Metalnem sorry for taking so long to get on this. Finally fixed this - feel free to grab the newly generated vectors:

https://raw.githubusercontent.com/mcginty/snow/master/tests/vectors/snow-multipsk.txt
