### ISSUE TITLE
test vectors only valid when nonce doesn't advance?

### ISSUE THREAD

**Issue by aep** [mcginty/snow#66]
i'm having trouble understanding the test vectors versus how nonce works.
as far as i understand the noise spec, every read and write will advance the nonce by one,
but the test vectors only work out if the nonce never advances. is this intentional or is my math wrong?

**Comment by mcginty** [comment]
In transport mode the nonce will increase by one, which should be the case since we [call `into_transport_mode()` in the vector test code](https://github.com/mcginty/snow/blob/master/tests/vectors.rs#L223). What math isn't working out?

**Comment by aep** [comment]
finally figured it out. the snow tests don't advance the nonce at all. i think they should, but it doesn't really matter.

the cacophony tests DO advance the nonce, but only after the 3rd message, because they assume tcp where transport starts in nonce 0, i guess.  

All of the tests now work out for me, thanks.

**Comment by mcginty** [comment]
@aep ah, maybe you're referring to the fact that the snow vectors don't generate transport messages while other libraries do?
