### ISSUE TITLE
expose get_remote_static

### ISSUE THREAD

**Issue by david415** [mcginty/snow#7]
HandshakeState has got a method called get_remote_static which isn't accessible from someone using this library because Session doesn't expose it. I think this should be exposed because protocol designs using Noise may well need to use this information for additional authentication steps. My use-case is well documented:

https://github.com/katzenpost/docs/blob/master/specs/wire-protocol.rst#handshake-authentication

Hopefully this sounds like a reasonable feature that you'd support. If so I can easily add the few lines this needs and submit a pull request.

**Comment by mcginty** [comment]
Yep, this actually [exists in my wireguard branch](https://github.com/mcginty/snow/blob/wireguard/src/session.rs#L143) (for changes necessary to cleanly work on my wireguard implementation), but I'd happily take a clean PR for the master branch.

**Comment by david415** [comment]
solved by @str4d in https://github.com/mcginty/snow/pull/13

**Comment by mcginty** [comment]
Fixed :)
