### ISSUE TITLE
Support XChaCha20Poly

### ISSUE THREAD

**Issue by Frando** [mcginty/snow#71]
I want to implement [hypercore-protocol](https://github.com/mafintosh/hypercore-protocol) in Rust. The protocol uses a NOISE handshake of the variant `Noise_XX_25519_XChaChaPoly_BLAKE2b`. So far, snow only implements `ChaChaPoly` but not `XChaChaPoly`.

`hypercore-protocol` in NodeJs uses crytpo from libsodium. It recently added `XChaChaPoly` (see [here](https://libsodium.gitbook.io/doc/secret-key_cryptography/aead#availability-and-interoperability)).

**Comment by tarcieri** [comment]
Note that the [`chacha20poly1305` crate](https://github.com/RustCrypto/AEADs/tree/master/chacha20poly1305) also supports XChaChaPoly

**Comment by Frando** [comment]
I wrote something up with the chacha20poly1305 crate: #73

**Comment by mcginty** [comment]
Thanks @Frando, taking a look now!

**Comment by Frando** [comment]
Closed by #73
