### ISSUE TITLE
alternatives to ring

### ISSUE THREAD

**Issue by aep** [mcginty/snow#9]
ring has an unfortunately messy license.

any chance to modularize this so it can be used on top of clean implementations of individual algorithms? specifically Curve25519 has a bunch of clean ones.

**Comment by mcginty** [comment]
just don't use the "ring-*" features and you won't be using ring.


On Fri, Apr 20, 2018, at 2:37 AM, Arvid E. Picciani wrote:
> ring has an unfortunately messy license.


> any chance to modularize this so it can be used on top of clean
> implementations of individual algorithms? specifically Curve25519 has
> a bunch of clean ones.> — You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub[1], or mute the
> thread[2].> 


Links:

  1. https://github.com/mcginty/snow/issues/9

**Comment by mcginty** [comment]
Closing, please reopen if any of my claims are in error (in that case it's a bug).
