### ISSUE TITLE
panic in handshake state

### ISSUE THREAD

**Issue by pawanjay176** [mcginty/snow#94]
Got this panic while trying to interop rust-libp2p noise (which uses snow) with go-libp2p noise. 
```
thread 'tokio-runtime-worker' panicked at 'index out of bounds: the len is 3 but the index is 3', /home/pawan/.cargo/registry/src/github.com-1ecc6299db9ec823/snow-0.6.2/src/handshakestate.rs:306:26
```
The panic is in `snow-0.6.2`, but the unchecked indexing exists in current master as well.
https://github.com/mcginty/snow/blob/master/src/handshakestate.rs#L359

**Comment by mcginty** [comment]
@pawanjay176 can you share what Noise pattern you're using?

**Comment by pawanjay176** [comment]
@mcginty  I'm using the XX pattern. This is the my full `NoiseParams` string `Noise_XX_25519_ChaChaPoly_SHA256`.

**Comment by mcginty** [comment]
Thanks very much @pawanjay176, that was an important catch. Will push a patch release for this.
